=== fire/tnf2/other/aj/fm/spells.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Aaron Judd (na) -->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Spell_List">
		<xs:annotation>
			<xs:documentation>List of all Spells</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="Spell">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="gesture">
								<xs:annotation>
									<xs:documentation>Gesture Sequence</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="name">
								<xs:annotation>
									<xs:documentation>Name of the spell</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="priority">
								<xs:annotation>
									<xs:documentation>Order in which spell effects lowest number first</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="description">
								<xs:annotation>
									<xs:documentation>Description of spell effects</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="delay" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Counter spells that will delay effects</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="cancel" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Counter spells that will cancel spell anytime</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="diffuse" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Counter spells that will stop effect if and only if cast on same turn</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="notes" minOccurs="0"/>
							<xs:element name="limited_game" minOccurs="0"/>
							<xs:element name="target" >
								<xs:annotation>
									<xs:documentation>Default target of spell effects</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fire/tnf2/other/aj/fm/engine/spells.xml
<?xml version="1.0" encoding="UTF-8"?><Spell_List xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="spells.xsd">	<Spell>		<gesture>V</gesture>		<name>Stab</name>		<priority>99</priority>		<description>*STAB* gesture *V*)\nThis is not a spell but an attack which can be directed at any individual monster or wizard. Unless protected in that turn by a Shield spell or another spell with the same effect, the being stabbed suffers 1 point of damage. The wizard only has one knife so can only stab with one hand in any turn, although which hand doesn't matter. The stab cannot be reflected by a Magic Mirror or stopped by Dispel Magic (although its Shield effect *could* stop the stab). Clumsy wizards are allowed to stab themselves. Knives cannot be thrown.\n</description>		<delay/>		<cancel>Shield</cancel>		<cancel>Dispel_Magic</cancel>		<cancel>Counter_Spell</cancel>		<cancel>Protection</cancel>		<diffuse/>	</Spell>	<Spell>		<gesture>P</gesture>		<name>Shield</name>		<priority>32</priority>		<description>*SHIELD* gesture *P* )\n\nThis spell protects the subject from all attacks from monsters (that is, creatures created by a summoning spell), from missile spells, and from stabs by wizards. The shield will block any number of such attacks but lasts for only one round. The shield protects the subject on the turn in which it is cast.\n</description>		<delay/>		<cancel/>		<diffuse>Dispel_Magic</diffuse>	</Spell>	<Spell>		<gesture>p</gesture>		<name>Surrender</name>		<priority>999</priority>		<description>*SURRENDER* (gestures *p* )\nThis is not a spell and consequently cannot be cast at anyone. The wizard making these gestures, irrespective of whether they terminate spells or not, surrenders and the contest is over. If the gestures do complete spells, those spells will be cast as usual - the surrender does not happen until the end of the round. The surrendering wizard is deemed to have lost unless his gestures completed spells which killed all remaining opponents, in which case he loses no points, but does not get any points either.\nTwo or more simultaneous surrenders count as a draw, and the victory points are divided between the surviving mages ... rounded down.\nIt is a skill for wizards to work their spells so that they never accidentally perform 2 *P* gestures simultaneously. It is too late to surrender on the turn you are killed - if you are killed as you make the surrender gesture, you will still die. However, if you live to the end of the turn, the referee will cure any diseases, poisons etc. in time for your next battle.\n</description>		<delay/>		<cancel/>		<diffuse/>	</Spell>	<Spell>		<gesture>cDPW</gesture>		<name>Dispel_Magic</name>		<priority>1</priority>		<description>*DISPEL MAGIC* (gestures *c D P W* )\n This spell acts as a combination of Counter_Spell and Remove Enchantment, but its effects are universal rather than limited to the subject of the spell. It will stop any spell cast in the same turn from working (apart from another Dispel Magic spell which combines with it for the same result), and will remove all enchantments from all beings before they have effect. In addition, all monsters are destroyed although they can attack that turn. Counter_Spells and Magic Mirrors have no effect. The spell will not work on stabs or surrenders. As with a Counter_Spell it also acts as a Shield for its subject.\n</description>		<delay/>		<cancel/>		<diffuse/>	</Spell>	<Spell>		<gesture>PSDF</gesture>		<name>Charm_Person</name>		<priority>21</priority>		<description>*Charm_Person* (gestures *P S D F* )\nExcept for cancellation with other enchantments, this spell only affects humans. The subject of the spell submits orders as normal, but the caster of the spell also submits an order for one of the subject's hands. (This is done using the 'DIRECT' order).\nThe server uses the order submitted by the caster for the subject's affected hand next turn. If the subject is only so because of a reflection from a Magic Mirror the subject of the mirror assumes the role of caster and decides his opponent's gesture. If the caster does not submit a 'DIRECT' command the following turn, the target will do his or her gestures as normal. If the subject is also the subject of any of Amnesia, Confusion, Charm_Monster, Fear, or another Charm_Person, then none of the spells work.\n</description>		<delay/>		<cancel/>		<diffuse>Amnesia</diffuse>		<diffuse>Confusion</diffuse>		<diffuse>Charm_Monster</diffuse>		<diffuse>Fear</diffuse>		<diffuse>Charm_Person</diffuse>	</Spell>	<Spell>		<gesture>cSWPP</gesture>		<name>Summon_Fire_Elemental</name>		<priority>8</priority>		<description>*SUMMON FIRE ELEMENTAL* ( *c S W P P (classic))\n This spell creates a fire elemental. Casting this spell will cause a elemental to be created, even if no target is specified.\n The elemental will, for that turn and until destroyed, attack everyon who is not resistant to its type (heat or cold), causing three points o damage per turn. The elemental takes three points of damage to be kille but may be destroyed by spells of the opposite type (e.g. Fire Storm Resist Cold or Fireball will kill an ice elemental), and will also neutralize the cancelling spell. Elementals will not attack on the turn they are destroyed by such a spell. An elemental will also be engulfe and destroyed by a storm of its own type but, in such an event, the storm is not neutralized although the elemental still does not attack i that turn.\n Two elementals of the opposite type will also destroy each other befor attacking, and two of the same type will join together to form a singl elemental of normal strength. Note that only wizards or monster resistant to the type of elemental, or who are casting a spell which ha the effect of a Shield do not get attacked by the elemental. Casting  Fireball upon yourself when being attacked by an ice elemental is no defence! (Cast it at the elemental...)\n</description>		<delay/>		<cancel/>		<diffuse/>		<limited_game>classic_only</limited_game>	</Spell>	<Spell>		<gesture>PSFW</gesture>		<name>Summon_Ogre</name>		<priority>5</priority>		<description>*SUMMON OGRE* (gestures *P S F W* )\n This spell is the same as Summon Goblin but the ogre created inflicts and is destroyed by two points of damage rather than one. The summoning spell cannot be cast at an elemental, and if cast at something which doesn't exist, the spell has no effect.\n</description>		<delay>Confusion</delay>		<delay>Amnisia</delay>		<delay>Paralysis</delay>		<delay>Fear</delay>		<cancel>Remove_Enchantment</cancel>		<cancel>Dispel_Magic</cancel>		<diffuse>Charm_Monster</diffuse>		<diffuse>Blindness</diffuse>		<diffuse>Invisibility</diffuse>	</Spell>	<Spell>		<gesture>cSWWS</gesture>		<name>Summon_Ice_Elemental</name>		<priority>9</priority>		<description>*SUMMON ICE ELEMENTAL* (gestures *c S W W S* )\n This spell creates an ice elemental. Casting this spell will cause an elemental to be created, even if no target is specified.\n The elemental will, for that turn and until destroyed, attack everyone who is not resistant to its type (heat or cold), causing three points of damage per turn. The elemental takes three points of damage to be killed but may be destroyed by spells of the opposite type (e.g. Fire Storm, Resist Cold or Fireball will kill an ice elemental), and will also neutralize the cancelling spell. Elementals will not attack on the turn they are destroyed by such a spell. An elemental will also be engulfed and destroyed by a storm of its own type but, in such an event, the storm is not neutralized although the elemental still does not attack in that turn.\n  Two elementals of the opposite type will also destroy each other before attacking, and two of the same type will join together to form a single elemental of normal strength. Note that only wizards or monsters resistant to the type of elemental, or who are casting a spell which has the effect of a Shield do not get attacked by the elemental. Casting a Fireball upon yourself when being attacked by an ice elemental is no defence! (Cast it at the elemental...)\n</description>		<delay>Shield</delay>		<delay>Magic_Mirror</delay>		<delay>Protection</delay>		<delay>Counter_Spell</delay>		<delay>Amnisia</delay>		<delay>Paralysis</delay>		<cancel>Ice_Storm</cancel>		<cancel>Remove_Enchantment</cancel>		<cancel>Dispel_Magic</cancel>		<diffuse>Fireball</diffuse>		<diffuse>Resist_Cold</diffuse>		<diffuse>Fire_Storm</diffuse>		<diffuse>Fire_Elemental</diffuse>		<diffuse>Blindness</diffuse>		<diffuse>Invisibility</diffuse>	</Spell>	<Spell>		<gesture>PWPFSSSD</gesture>		<name>Finger_Of_Death</name>		<priority>38</priority>		<description>*FINGER OF DEATH* (gestures *P W P F S S S D* )\nKills the subject stone dead. This spell is so powerful that it is unaffected by a Counter_Spell, although a Dispel Magic spell cast upon the final gesture will stop it. The usual way to prevent being harmed by this spell is to disrupt it during casting, using, for example, an Anti Spell. If the target is subject to both Raise Dead and Finger of Death, the two spells will cancel each other.\n</description>		<delay/>		<cancel/>		<diffuse>Dispel_Magic</diffuse>		<diffuse>Raise_Dead</diffuse>	</Spell>	<Spell>		<gesture>cWSSW</gesture>		<name>Summon_Fire_Elemental</name>		<priority>8</priority>		<description>*SUMMON FIRE ELEMENTAL* (gestures *c W S S W* )\nThis spell creates a fire elemental. Casting this spell will cause an elemental to be created, even if no target is specified. The elemental will, for that turn and until destroyed, attack everyone who is not resistant to its type (heat or cold), causing three points of damage per turn. The elemental takes three points of damage to be killed but may be destroyed by spells of the opposite type (e.g. Fire Storm, Resist Cold or Fireball will kill an ice elemental), and will also ne
